[workspace]
exclude = ["vendor"]
resolver = "2"
members = [
    "crates/chainspec",
    "crates/validators",
    "crates/consensus/traits",
    "crates/consensus/simplex",
    "crates/network/traits",
    "crates/network/commonware",
    "crates/app/execute/evm/rpc",
    "crates/app/execute/mem/rpc",
    "crates/node",
    "crates/app/state",
    "crates/app/execute/mem/state",
    "crates/app/execute/evm/state",
    "crates/app/traits",
    "crates/app/execute/evm/app",
    "crates/app/execute/evm/precompiles",
    "crates/app/execute/mem/composite",
    "crates/app/execute/mem/app",
    "crates/app/execute/mem/tx-dispatch",
    "crates/mempool/traits",
    "crates/mempool/mdbx",
    "testing/integration-tests",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
