[workspace]
exclude = ["vendor"]
resolver = "2"
members = [
    "crates/consensus",
    "crates/consensus-simplex",
    "crates/p2p",
    "crates/p2p-commonware",
    "crates/whirlpool-node",
    "crates/state",
    "crates/app",
    "crates/app-evm",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
