[package]
name = "app-evm"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
app = { path = "../../app" }
community-pool = { path = "../../community-pool" }
evm-precompiles = { path = "../precompiles" }
native-token = { path = "../../native-token" }
validators = { path = "../../validators" }
state = { path = "../../state" }
state-memory = { path = "../../mem/state" }
state-reth = { path = "../state" }
consensus = { path = "../../consensus" }
reth-evm = { path = "../../../vendor/reth/crates/evm/evm" }
reth-evm-ethereum = { path = "../../../vendor/reth/crates/ethereum/evm" }
reth-ethereum-primitives = { path = "../../../vendor/reth/crates/ethereum/primitives" }
reth-revm = { path = "../../../vendor/reth/crates/revm" }
reth-execution-types = { path = "../../../vendor/reth/crates/evm/execution-types" }
reth-execution-errors = { path = "../../../vendor/reth/crates/evm/execution-errors" }
reth-primitives-traits = { path = "../../../vendor/reth/crates/primitives-traits" }
reth-chainspec = { path = "../../../vendor/reth/crates/chainspec" }
alloy-consensus = "1.4.3"
alloy-eips = "1.4.3"
alloy-genesis = "1.0.31"
alloy-primitives = "1.5.0"
revm = "34"
thiserror = "2"
alloy-trie = "0.9"

[dev-dependencies]
futures = "0.3"
tokio = { version = "1", features = ["rt", "macros"] }
