listen_addr = "127.0.0.1:4015"
dialable_addr = "127.0.0.1:4015"
validator_seed = 77
rpc_addr = "127.0.0.1:9545"
mem_rpc_addr = "127.0.0.1:9645"
data_dir = "devtools/demo/personality/.run/data"
network_namespace = "demo-personality-network"
consensus_namespace = "demo-personality-consensus"
block_interval_ms = 1000
