[package]
name = "chainspec"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
app-evm-execution = { path = "../app/evm/execution" }
evm-precompiles = { path = "../precompiles/evm" }
validators = { path = "../validators" }
reth-chainspec = { path = "../../vendor/reth/crates/chainspec" }
alloy-genesis = "1.0.31"
alloy-primitives = "1.5.0"
thiserror = "2"
