[package]
name = "whirlpool-node"
version.workspace = true
edition.workspace = true

[dependencies]
app = { path = "../app/traits" }
app-evm-execution = { path = "../app/evm/execution" }
chainspec = { path = "../chainspec" }
mempool-mdbx = { path = "../mempool/mdbx" }
validators-reader = { path = "../validators/reader" }
validators-dkg = { path = "../validators/dkg" }
rpc-eth = { path = "../rpc/evm" }
reth-chainspec = { path = "../../vendor/reth/crates/chainspec" }
state = { path = "../app/state" }
app-evm-state = { path = "../app/evm/state-reth" }
revm = { version = "36" }
alloy-primitives = { version = "1.5.0" }
consensus = { path = "../consensus/traits" }
consensus-simplex = { path = "../consensus/simplex" }
consensus-manager = { path = "../consensus/manager" }
network-commonware = { path = "../network/commonware" }
commonware-cryptography = { path = "../../vendor/commonware/cryptography" }
commonware-codec = { path = "../../vendor/commonware/codec" }
commonware-p2p = { path = "../../vendor/commonware/p2p" }
commonware-utils = { path = "../../vendor/commonware/utils" }
commonware-runtime = { path = "../../vendor/commonware/runtime" }
sha2 = "0.10"
bytes = "1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"


[[bin]]
name = "whirlpool-node"
path = "src/main.rs"
