[package]
name = "consensus-simplex"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
consensus = { path = "../traits" }
network = { path = "../../network/traits", features = ["mock"] }
network-commonware = { path = "../../network/commonware" }
commonware-consensus = { git = "https://github.com/commonwarexyz/monorepo", tag = "v2026.7.1" }
commonware-broadcast = { git = "https://github.com/commonwarexyz/monorepo", tag = "v2026.7.1" }
commonware-cryptography = { git = "https://github.com/commonwarexyz/monorepo", tag = "v2026.7.1" }
commonware-p2p = { git = "https://github.com/commonwarexyz/monorepo", tag = "v2026.7.1" }
commonware-runtime = { git = "https://github.com/commonwarexyz/monorepo", tag = "v2026.7.1" }
commonware-storage = { git = "https://github.com/commonwarexyz/monorepo", tag = "v2026.7.1" }
commonware-codec = { git = "https://github.com/commonwarexyz/monorepo", tag = "v2026.7.1" }
commonware-utils = { git = "https://github.com/commonwarexyz/monorepo", tag = "v2026.7.1" }
commonware-parallel = { git = "https://github.com/commonwarexyz/monorepo", tag = "v2026.7.1" }
commonware-actor = { git = "https://github.com/commonwarexyz/monorepo", tag = "v2026.7.1" }

tokio = { version = "1", features = ["rt", "sync", "macros"] }
tracing = "0.1"
futures = "0.3"
rand = "0.10"
rand_core = "0.10"
bytes = "1"

[dev-dependencies]
